GET http://127.0.0.1:3000/API/v1/products

###

GET http://127.0.0.1:3000/API/v1/products/1

###

GET http://127.0.0.1:3000/API/v1/products/18

###

POST http://127.0.0.1:3000/API/v1/products/
Content-Type: application/json

{
  "name": "Primitivo",
  "price": 19.99,
  "description": "Il vino di Torve."
}
